local fzf_bg0='{{ hex bg0 }}'
local fzf_bg1='{{ hex bg1 }}'
local fzf_bg2='{{ hex bg2 }}'
local fzf_bg3='{{ hex bg3 }}'
local fzf_bg4='{{ hex bg4 }}'
local fzf_fg4='{{ hex fg4 }}'
local fzf_fg3='{{ hex fg3 }}'
local fzf_fg2='{{ hex fg2 }}'
local fzf_fg1='{{ hex fg1 }}'
local fzf_fg0='{{ hex fg0 }}'

local fzf_red='{{ hex red }}'
local fzf_green='{{ hex green }}'
local fzf_yellow='{{ hex yellow }}'
local fzf_blue='{{ hex blue }}'
local fzf_magenta='{{ hex magenta }}'
local fzf_cyan='{{ hex cyan }}'
local fzf_orange='{{ hex orange }}'

local fzf_brightRed='{{ hex brightRed }}'
local fzf_brightGreen='{{ hex brightGreen }}'
local fzf_brightYellow='{{ hex brightYellow }}'
local fzf_brightBlue='{{ hex brightBlue }}'
local fzf_brightMagenta='{{ hex brightMagenta }}'
local fzf_brightCyan='{{ hex brightCyan }}'
local fzf_brightOrange='{{ hex brightOrange }}'
