fzf_bg0='{{ hex bg0 }}'
fzf_bg1='{{ hex bg1 }}'
fzf_bg2='{{ hex bg2 }}'
fzf_bg3='{{ hex bg3 }}'
fzf_bg4='{{ hex bg4 }}'
fzf_fg4='{{ hex fg4 }}'
fzf_fg3='{{ hex fg3 }}'
fzf_fg2='{{ hex fg2 }}'
fzf_fg1='{{ hex fg1 }}'
fzf_fg0='{{ hex fg0 }}'

fzf_red='{{ hex red }}'
fzf_green='{{ hex green }}'
fzf_yellow='{{ hex yellow }}'
fzf_blue='{{ hex blue }}'
fzf_magenta='{{ hex magenta }}'
fzf_cyan='{{ hex cyan }}'
fzf_orange='{{ hex orange }}'

fzf_brightRed='{{ hex brightRed }}'
fzf_brightGreen='{{ hex brightGreen }}'
fzf_brightYellow='{{ hex brightYellow }}'
fzf_brightBlue='{{ hex brightBlue }}'
fzf_brightMagenta='{{ hex brightMagenta }}'
fzf_brightCyan='{{ hex brightCyan }}'
fzf_brightOrange='{{ hex brightOrange }}'
